/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:24:07 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITextContentView.h>

@class PSTextViewTableCell;

@interface PSTextView : UITextContentView {

	PSTextViewTableCell* _cell;

}
-(void)setCell:(id)arg1 ;
@end

